// Code generated by RPL. DO NOT EDIT.
package sql

import (
	"context"
	"fmt"
	modelpkg "github.com/CandyCrafts/candy/internal/database/cache/cache_cli_text"
	"sort"
	"strings"
)

// cacheCliTextSQLBuildWhere собирает SQL WHERE-часть и аргументы из карты фильтров.
func cacheCliTextSQLBuildWhere(filters map[string]any, startIndex int) (string, []any, error) {
	if len(filters) == 0 {
		return "", nil, nil
	}

	keys := make([]string, 0, len(filters))
	for key := range filters {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	parts := make([]string, 0, len(keys))
	args := make([]any, 0, len(keys))

	for _, key := range keys {
		column, ok := cacheCliTextSQLNormalizeColumnName(key)
		if !ok {
			return "", nil, fmt.Errorf("unknown sql filter column %q", key)
		}

		value, err := cacheCliTextSQLNormalizeFilterValue(column, filters[key])
		if err != nil {
			return "", nil, err
		}

		if value == nil {
			parts = append(parts, column+" IS NULL")
			continue
		}

		args = append(args, value)
		parts = append(parts, fmt.Sprintf("%s = %s", column, cacheCliTextSQLPlaceholder(column, startIndex+len(args)-1)))
	}

	return " WHERE " + strings.Join(parts, " AND "), args, nil
}

// cacheCliTextSQLQueryMany выполняет SQL-запрос и собирает список моделей CacheCliText.
func cacheCliTextSQLQueryMany(ctx context.Context, db Executor, query string, args ...any) ([]modelpkg.CacheCliText, error) {
	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]modelpkg.CacheCliText, 0)
	for rows.Next() {
		var item modelpkg.CacheCliText
		if err := cacheCliTextSQLScan(rows, &item); err != nil {
			return nil, err
		}
		items = append(items, item)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// SQLInit создает таблицу и вспомогательные индексы для модели CacheCliText.
func Init(ctx context.Context, db Executor) error {
	for _, statement := range cacheCliTextSQLCreateStatements {
		if strings.TrimSpace(statement) == "" {
			continue
		}

		if _, err := db.ExecContext(ctx, statement); err != nil {
			return err
		}
	}

	return nil
}

// SQLCreate вставляет текущую модель CacheCliText в базу данных.
func Create(ctx context.Context, db Executor, model modelpkg.CacheCliText) error {
	values, err := cacheCliTextSQLDriverValues(model)
	if err != nil {
		return err
	}

	_, err = db.ExecContext(ctx, cacheCliTextSQLInsertStatement, values...)
	return err
}

// SQLGet находит одну модель CacheCliText по фильтрам.
func Get(ctx context.Context, db Executor, filters map[string]any) (modelpkg.CacheCliText, error) {
	if len(filters) == 0 {
		return modelpkg.CacheCliText{}, fmt.Errorf("SQLGet requires at least one filter")
	}

	where, args, err := cacheCliTextSQLBuildWhere(filters, 1)
	if err != nil {
		return modelpkg.CacheCliText{}, err
	}

	query := cacheCliTextSQLSelectStatement + where + " LIMIT 1"
	row := db.QueryRowContext(ctx, query, args...)
	var item modelpkg.CacheCliText
	if err := cacheCliTextSQLScan(row, &item); err != nil {
		return modelpkg.CacheCliText{}, err
	}

	return item, nil
}

// SQLUpdate обновляет запись модели CacheCliText по переданным фильтрам.
func Update(ctx context.Context, db Executor, model modelpkg.CacheCliText, filters map[string]any) error {
	if len(filters) == 0 {
		return fmt.Errorf("SQLUpdate requires at least one filter")
	}

	assignments, args, err := cacheCliTextSQLBuildUpdateAssignments(model, 1)
	if err != nil {
		return err
	}

	where, whereArgs, err := cacheCliTextSQLBuildWhere(filters, len(args)+1)
	if err != nil {
		return err
	}

	query := "UPDATE " + cacheCliTextSQLTableName + " SET " + assignments + where
	_, err = db.ExecContext(ctx, query, append(args, whereArgs...)...)
	return err
}

// SQLDelete удаляет записи модели CacheCliText по фильтрам.
func Delete(ctx context.Context, db Executor, filters map[string]any) error {
	if len(filters) == 0 {
		return fmt.Errorf("SQLDelete requires at least one filter")
	}

	where, args, err := cacheCliTextSQLBuildWhere(filters, 1)
	if err != nil {
		return err
	}

	query := "DELETE FROM " + cacheCliTextSQLTableName + where
	_, err = db.ExecContext(ctx, query, args...)
	return err
}

// SQLList возвращает список моделей CacheCliText с пагинацией.
func List(ctx context.Context, db Executor, limit int, offset int) ([]modelpkg.CacheCliText, error) {
	query := cacheCliTextSQLSelectStatement
	if orderBy := cacheCliTextSQLOrderByColumn; orderBy != "" {
		query += " ORDER BY " + orderBy
	}

	args := make([]any, 0, 2)
	if limit > 0 {
		args = append(args, limit)
		query += " LIMIT " + cacheCliTextSQLPlaceholder("", len(args))
	}
	if offset > 0 {
		args = append(args, offset)
		query += " OFFSET " + cacheCliTextSQLPlaceholder("", len(args))
	}

	return cacheCliTextSQLQueryMany(ctx, db, query, args...)
}

// SQLSearch ищет модели CacheCliText по текстовому запросу.
func Search(ctx context.Context, db Executor, term string, limit int, offset int) ([]modelpkg.CacheCliText, error) {
	trimmed := strings.TrimSpace(term)
	if trimmed == "" || len(cacheCliTextSQLSearchColumns) == 0 {
		return List(ctx, db, limit, offset)
	}

	pattern := "%" + trimmed + "%"
	parts := make([]string, 0, len(cacheCliTextSQLSearchColumns))
	args := make([]any, 0, len(cacheCliTextSQLSearchColumns)+2)
	for _, column := range cacheCliTextSQLSearchColumns {
		args = append(args, pattern)
		parts = append(parts, fmt.Sprintf("LOWER(%s) LIKE LOWER(%s)", column, cacheCliTextSQLPlaceholder(column, len(args))))
	}

	query := cacheCliTextSQLSelectStatement + " WHERE (" + strings.Join(parts, " OR ") + ")"
	if orderBy := cacheCliTextSQLOrderByColumn; orderBy != "" {
		query += " ORDER BY " + orderBy
	}
	if limit > 0 {
		args = append(args, limit)
		query += " LIMIT " + cacheCliTextSQLPlaceholder("", len(args))
	}
	if offset > 0 {
		args = append(args, offset)
		query += " OFFSET " + cacheCliTextSQLPlaceholder("", len(args))
	}

	return cacheCliTextSQLQueryMany(ctx, db, query, args...)
}
