// Code generated by RPL. DO NOT EDIT.
package sql

import (
	"context"
	stdsql "database/sql"
)

type Executor interface {
	ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *stdsql.Row
}

const cacheCliTextSQLTableName = "CacheCliText"

var cacheCliTextSQLColumnNames = []string{"lang", "text", "created_at"}

var cacheCliTextSQLSearchColumns = []string{"lang", "text"}

const cacheCliTextSQLSelectStatement = "SELECT lang, text, created_at FROM CacheCliText"

const cacheCliTextSQLOrderByColumn = "lang"

var cacheCliTextSQLCreateStatements = []string{
	"CREATE TABLE IF NOT EXISTS CacheCliText (\\n    lang TEXT NOT NULL,\\n    text TEXT NOT NULL,\\n    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP\\n);",
	"CREATE INDEX IF NOT EXISTS idx_CacheCliText_lang ON CacheCliText (lang);",
}

const cacheCliTextSQLInsertStatement = "INSERT INTO CacheCliText (lang, text, created_at) VALUES (?, ?, ?);"
