package main

import (
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

const defaultVersionFile = "pkg/branding/version.gen.go"

func main() {
	path := defaultVersionFile
	if len(os.Args) > 1 {
		path = os.Args[1]
	}

	version, err := incrementReleaseVersion(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Printf("release version: %s\n", version)
}

func incrementReleaseVersion(path string) (string, error) {
	return incrementReleaseVersionAt(path, time.Now())
}

func incrementReleaseVersionAt(path string, now time.Time) (string, error) {
	current, err := readReleaseVersion(path)
	if err != nil {
		return "", err
	}
	version, err := nextReleaseVersion(current, now)
	if err != nil {
		return "", err
	}

	if err := writeReleaseVersion(path, version); err != nil {
		return "", err
	}
	return version, nil
}

func nextReleaseVersion(current string, now time.Time) (string, error) {
	today := now.Format("06.1.2")
	if current == "" {
		return today + ".1", nil
	}

	parts := strings.Split(current, ".")
	if len(parts) != 4 {
		return "", fmt.Errorf("invalid release version %q: expected YY.M.D.N", current)
	}
	date := strings.Join(parts[:3], ".")
	if _, err := time.Parse("06.1.2", date); err != nil {
		return "", fmt.Errorf("invalid release version date %q: %w", date, err)
	}
	if date != today {
		return today + ".1", nil
	}

	sequence, err := strconv.ParseUint(parts[3], 10, 64)
	if err != nil {
		return "", fmt.Errorf("invalid release sequence %q: %w", parts[3], err)
	}
	if sequence == math.MaxUint64 {
		return "", errors.New("release sequence overflow")
	}
	return fmt.Sprintf("%s.%d", today, sequence+1), nil
}

func readReleaseVersion(path string) (string, error) {
	source, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return "", nil
	}
	if err != nil {
		return "", fmt.Errorf("read release version: %w", err)
	}

	file, err := parser.ParseFile(token.NewFileSet(), path, source, 0)
	if err != nil {
		return "", fmt.Errorf("parse release version: %w", err)
	}

	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.VAR {
			continue
		}
		for _, specification := range general.Specs {
			value, ok := specification.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for index, name := range value.Names {
				if name.Name != "ReleaseVersion" || index >= len(value.Values) {
					continue
				}
				literal, ok := value.Values[index].(*ast.BasicLit)
				if !ok || literal.Kind != token.STRING {
					return "", errors.New("ReleaseVersion must be a string literal")
				}
				version, err := strconv.Unquote(literal.Value)
				if err != nil {
					return "", fmt.Errorf("parse ReleaseVersion: %w", err)
				}
				return version, nil
			}
		}
	}

	return "", errors.New("ReleaseVersion variable not found")
}

func writeReleaseVersion(path string, version string) error {
	source := []byte(fmt.Sprintf(`// Code generated by go run ./cmd/version. DO NOT EDIT.

package branding

var ReleaseVersion string = %q
`, version))
	formatted, err := format.Source(source)
	if err != nil {
		return fmt.Errorf("format release version: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create branding directory: %w", err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("write release version: %w", err)
	}
	return nil
}
