// Code generated by RPL. DO NOT EDIT.
// Generated at: 2026-07-22T01:30:42+03:00
// RPL version: 0.7.3
// Author: <rpl>
package plugin

import (
	pluginpubinfo "github.com/caramelang/caramel/internal/models/plugin_pub_info"
)

// Plugin описывает сгенерированную модель данных.
type Plugin struct {
	PubInfo        pluginpubinfo.PluginPubInfo
	PathPluginSave string
	WasmBin        []byte
	IsGlobal       bool
}

// DefaultPlugin создает Plugin со значениями полей по умолчанию.
func DefaultPlugin() Plugin {
	return Plugin{
		IsGlobal: true,
	}
}
