// Code generated by RPL. DO NOT EDIT.
package sql

import (
	"context"
	"fmt"
	modelpkg "github.com/caramelang/caramel/internal/models/sql_plugin"
	"sort"
	"strings"
)

// sqlPluginSQLBuildWhere собирает SQL WHERE-часть и аргументы из карты фильтров.
func sqlPluginSQLBuildWhere(filters map[string]any, startIndex int) (string, []any, error) {
	if len(filters) == 0 {
		return "", nil, nil
	}

	keys := make([]string, 0, len(filters))
	for key := range filters {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	parts := make([]string, 0, len(keys))
	args := make([]any, 0, len(keys))

	for _, key := range keys {
		column, ok := sqlPluginSQLNormalizeColumnName(key)
		if !ok {
			return "", nil, fmt.Errorf("unknown sql filter column %q", key)
		}

		value, err := sqlPluginSQLNormalizeFilterValue(key, filters[key])
		if err != nil {
			return "", nil, err
		}

		if value == nil {
			parts = append(parts, column+" IS NULL")
			continue
		}

		args = append(args, value)
		parts = append(parts, fmt.Sprintf("%s = %s", column, sqlPluginSQLPlaceholder(column, startIndex+len(args)-1)))
	}

	return " WHERE " + strings.Join(parts, " AND "), args, nil
}

// sqlPluginSQLAppendPagination безопасно добавляет LIMIT/OFFSET для выбранного SQL-диалекта.
func sqlPluginSQLAppendPagination(query string, args []any, limit int, offset int) (string, []any) {
	if limit > 0 {
		args = append(args, limit)
		query += " LIMIT " + sqlPluginSQLPlaceholder("", len(args))
	}
	if offset > 0 {
		args = append(args, offset)
		query += " OFFSET " + sqlPluginSQLPlaceholder("", len(args))
	}
	return query, args
}

// sqlPluginSQLQueryMany выполняет SQL-запрос и собирает список моделей SqlPlugin.
func sqlPluginSQLQueryMany(ctx context.Context, db Executor, query string, args ...any) ([]modelpkg.SqlPlugin, error) {
	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]modelpkg.SqlPlugin, 0)
	for rows.Next() {
		var item modelpkg.SqlPlugin
		if err := sqlPluginSQLScan(rows, &item); err != nil {
			return nil, err
		}
		items = append(items, item)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// SQLInit создает таблицу и вспомогательные индексы для модели SqlPlugin.
func Init(ctx context.Context, db Executor) error {
	for _, statement := range sqlPluginSQLCreateStatements {
		if strings.TrimSpace(statement) == "" {
			continue
		}

		if _, err := db.ExecContext(ctx, statement); err != nil {
			return err
		}
	}

	return nil
}

// SQLCreate вставляет текущую модель SqlPlugin в базу данных.
func Create(ctx context.Context, db Executor, model modelpkg.SqlPlugin) error {
	values, err := sqlPluginSQLDriverValues(model)
	if err != nil {
		return err
	}

	_, err = db.ExecContext(ctx, sqlPluginSQLInsertStatement, values...)
	return err
}

// SQLGet находит одну модель SqlPlugin по фильтрам.
func Get(ctx context.Context, db Executor, filters map[string]any) (modelpkg.SqlPlugin, error) {
	if len(filters) == 0 {
		return modelpkg.SqlPlugin{}, fmt.Errorf("SQLGet requires at least one filter")
	}

	where, args, err := sqlPluginSQLBuildWhere(filters, 1)
	if err != nil {
		return modelpkg.SqlPlugin{}, err
	}

	query := sqlPluginSQLSelectStatement + where + " LIMIT 1"
	row := db.QueryRowContext(ctx, query, args...)
	var item modelpkg.SqlPlugin
	if err := sqlPluginSQLScan(row, &item); err != nil {
		return modelpkg.SqlPlugin{}, err
	}

	return item, nil
}

// SQLUpdate обновляет запись модели SqlPlugin по переданным фильтрам.
func Update(ctx context.Context, db Executor, model modelpkg.SqlPlugin, filters map[string]any) error {
	if len(filters) == 0 {
		return fmt.Errorf("SQLUpdate requires at least one filter")
	}

	assignments, args, err := sqlPluginSQLBuildUpdateAssignments(model, 1)
	if err != nil {
		return err
	}

	where, whereArgs, err := sqlPluginSQLBuildWhere(filters, len(args)+1)
	if err != nil {
		return err
	}

	query := "UPDATE " + sqlPluginSQLTableName + " SET " + assignments + where
	_, err = db.ExecContext(ctx, query, append(args, whereArgs...)...)
	return err
}

// SQLDelete удаляет записи модели SqlPlugin по фильтрам.
func Delete(ctx context.Context, db Executor, filters map[string]any) error {
	if len(filters) == 0 {
		return fmt.Errorf("SQLDelete requires at least one filter")
	}

	where, args, err := sqlPluginSQLBuildWhere(filters, 1)
	if err != nil {
		return err
	}

	query := "DELETE FROM " + sqlPluginSQLTableName + where
	_, err = db.ExecContext(ctx, query, args...)
	return err
}

// SQLList возвращает список моделей SqlPlugin с пагинацией.
func List(ctx context.Context, db Executor, limit int, offset int) ([]modelpkg.SqlPlugin, error) {
	query := sqlPluginSQLSelectStatement
	if orderBy := sqlPluginSQLOrderByColumn; orderBy != "" {
		query += " ORDER BY " + orderBy
	}

	query, args := sqlPluginSQLAppendPagination(query, nil, limit, offset)

	return sqlPluginSQLQueryMany(ctx, db, query, args...)
}

// SQLSearch ищет модели SqlPlugin по текстовому запросу.
func Search(ctx context.Context, db Executor, term string, limit int, offset int) ([]modelpkg.SqlPlugin, error) {
	trimmed := strings.TrimSpace(term)
	if trimmed == "" || len(sqlPluginSQLSearchColumns) == 0 {
		return List(ctx, db, limit, offset)
	}

	pattern := "%" + trimmed + "%"
	parts := make([]string, 0, len(sqlPluginSQLSearchColumns))
	args := make([]any, 0, len(sqlPluginSQLSearchColumns)+2)
	for _, column := range sqlPluginSQLSearchColumns {
		args = append(args, pattern)
		parts = append(parts, fmt.Sprintf("LOWER(%s) LIKE LOWER(%s)", column, sqlPluginSQLPlaceholder(column, len(args))))
	}

	query := sqlPluginSQLSelectStatement + " WHERE (" + strings.Join(parts, " OR ") + ")"
	if orderBy := sqlPluginSQLOrderByColumn; orderBy != "" {
		query += " ORDER BY " + orderBy
	}
	query, args = sqlPluginSQLAppendPagination(query, args, limit, offset)

	return sqlPluginSQLQueryMany(ctx, db, query, args...)
}

// Store хранит SQL executor для операций модели SqlPlugin.
type Store struct {
	db Executor
}

// NewStore создает SQL store для модели SqlPlugin.
func NewStore(db Executor) *Store {
	return &Store{db: db}
}

func (store *Store) executor() (Executor, error) {
	if store == nil || store.db == nil {
		return nil, fmt.Errorf("sql store executor is nil")
	}
	return store.db, nil
}

func (store *Store) DB() Executor {
	if store == nil {
		return nil
	}
	return store.db
}

func (store *Store) WithExecutor(db Executor) *Store {
	return NewStore(db)
}

func (store *Store) Init(ctx context.Context) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Init(ctx, db)
}

func (store *Store) Create(ctx context.Context, model modelpkg.SqlPlugin) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Create(ctx, db, model)
}

func (store *Store) Get(ctx context.Context, filters map[string]any) (modelpkg.SqlPlugin, error) {
	db, err := store.executor()
	if err != nil {
		return modelpkg.SqlPlugin{}, err
	}
	return Get(ctx, db, filters)
}

func (store *Store) Update(ctx context.Context, model modelpkg.SqlPlugin, filters map[string]any) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Update(ctx, db, model, filters)
}

func (store *Store) Delete(ctx context.Context, filters map[string]any) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Delete(ctx, db, filters)
}

func (store *Store) List(ctx context.Context, limit int, offset int) ([]modelpkg.SqlPlugin, error) {
	db, err := store.executor()
	if err != nil {
		return nil, err
	}
	return List(ctx, db, limit, offset)
}

func (store *Store) Search(ctx context.Context, term string, limit int, offset int) ([]modelpkg.SqlPlugin, error) {
	db, err := store.executor()
	if err != nil {
		return nil, err
	}
	return Search(ctx, db, term, limit, offset)
}
