// Code generated by RPL. DO NOT EDIT.
package sql

import (
	stdsql "database/sql"
	"encoding/json"
	"fmt"
	modelpkg "github.com/caramelang/caramel/internal/models/sql_plugin"
	"strings"
	"time"
)

// sqlDriverValues подготавливает значения модели SqlPlugin для SQL-запросов.
func sqlPluginSQLDriverValues(model modelpkg.SqlPlugin) ([]any, error) {
	values := make([]any, 0, len(sqlPluginSQLColumnNames))
	now := time.Now()
	payloadPlugin, err := sqlPluginSQLMarshalJSON(model.Plugin)
	if err != nil {
		return nil, err
	}
	values = append(values, payloadPlugin)
	if model.UpdateAt.IsZero() {
		values = append(values, now)
	} else {
		values = append(values, model.UpdateAt)
	}
	if model.CreatedAt.IsZero() {
		values = append(values, now)
	} else {
		values = append(values, model.CreatedAt)
	}
	return values, nil
}

// sqlPluginSQLPlaceholder строит SQL placeholder для конкретной колонки.
func sqlPluginSQLPlaceholder(columnName string, index int) string {
	column, ok := sqlPluginSQLNormalizeColumnName(columnName)
	if !ok {
		return fmt.Sprintf("$%d", index)
	}
	switch column {
	case "\"plugin\"":
		return fmt.Sprintf("$%d::JSONB", index)
	default:
		return fmt.Sprintf("$%d", index)
	}
}

// sqlPluginSQLNormalizeColumnName нормализует имя поля модели в имя SQL-колонки.
func sqlPluginSQLNormalizeColumnName(name string) (string, bool) {
	switch strings.TrimSpace(name) {
	case "Plugin", "plugin":
		return "\"plugin\"", true
	case "UpdateAt", "update_at":
		return "\"update_at\"", true
	case "CreatedAt", "created_at":
		return "\"created_at\"", true
	default:
		return "", false
	}
}

// sqlPluginSQLNormalizeFilterValue приводит значение фильтра к SQL-совместимому виду.
func sqlPluginSQLNormalizeFilterValue(columnName string, value any) (any, error) {
	column, ok := sqlPluginSQLNormalizeColumnName(columnName)
	if !ok {
		return nil, fmt.Errorf("unknown sql filter column %q", columnName)
	}
	if value == nil {
		return nil, nil
	}
	switch column {
	case "\"plugin\"":
		return sqlPluginSQLMarshalJSON(value)
	default:
		return value, nil
	}
}

// sqlBuildUpdateAssignments подготавливает SET-часть UPDATE для модели SqlPlugin.
func sqlPluginSQLBuildUpdateAssignments(model modelpkg.SqlPlugin, startIndex int) (string, []any, error) {
	values, err := sqlPluginSQLDriverValues(model)
	if err != nil {
		return "", nil, err
	}
	sqlPluginSQLTouchUpdatedAt(values)
	if len(sqlPluginSQLUpdateColumnIndexes) == 0 {
		return "", nil, fmt.Errorf("model SqlPlugin has no mutable SQL columns")
	}

	columns := sqlPluginSQLColumnNames
	parts := make([]string, 0, len(sqlPluginSQLUpdateColumnIndexes))
	args := make([]any, 0, len(sqlPluginSQLUpdateColumnIndexes))

	for _, index := range sqlPluginSQLUpdateColumnIndexes {
		column := columns[index]
		parts = append(parts, fmt.Sprintf("%s = %s", column, sqlPluginSQLPlaceholder(column, startIndex+len(args))))
		args = append(args, values[index])
	}

	return strings.Join(parts, ", "), args, nil
}

// sqlScan заполняет модель SqlPlugin данными из SQL scanner.
func sqlPluginSQLScan(scanner interface{ Scan(dest ...any) error }, model *modelpkg.SqlPlugin) error {
	var pluginRaw any
	var updateAtValue stdsql.NullTime
	var createdAtValue stdsql.NullTime
	if err := scanner.Scan(&pluginRaw, &updateAtValue, &createdAtValue); err != nil {
		return err
	}
	if err := sqlPluginSQLDecodeJSON(pluginRaw, &model.Plugin); err != nil {
		return err
	}
	if !updateAtValue.Valid {
		return fmt.Errorf("required sql time column %q was NULL", "update_at")
	}
	model.UpdateAt = updateAtValue.Time
	if !createdAtValue.Valid {
		return fmt.Errorf("required sql time column %q was NULL", "created_at")
	}
	model.CreatedAt = createdAtValue.Time
	return nil
}

func sqlPluginSQLTouchUpdatedAt(values []any) {
	now := time.Now()
	for _, index := range []int{1} {
		if index >= 0 && index < len(values) {
			values[index] = now
		}
	}
}

// sqlPluginSQLMarshalJSON сериализует значение в JSON-строку для SQL хранения.
func sqlPluginSQLMarshalJSON(value any) (string, error) {
	body, err := json.Marshal(value)
	if err != nil {
		return "", err
	}

	return string(body), nil
}

// sqlPluginSQLDecodeJSON восстанавливает JSON-значение из сырого SQL-поля.
func sqlPluginSQLDecodeJSON(value any, target any) error {
	body, err := sqlPluginSQLRawBytes(value)
	if err != nil {
		return err
	}
	if len(body) == 0 {
		return nil
	}

	return json.Unmarshal(body, target)
}

// sqlPluginSQLRawBytes приводит сырое SQL-значение к байтам.
func sqlPluginSQLRawBytes(value any) ([]byte, error) {
	switch typed := value.(type) {
	case nil:
		return nil, nil
	case []byte:
		return typed, nil
	case string:
		return []byte(typed), nil
	default:
		return nil, fmt.Errorf("unsupported raw sql value %T", value)
	}
}
