// Code generated by RPL. DO NOT EDIT.
package sql

import (
	"context"
	stdsql "database/sql"
)

type Executor interface {
	ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *stdsql.Row
}

const TableName = "sql_plugin"

const sqlPluginSQLTableName = "\"sql_plugin\""

type Column string

const (
	ColumnPlugin    Column = "plugin"
	ColumnUpdateAt  Column = "update_at"
	ColumnCreatedAt Column = "created_at"
)

func (column Column) String() string {
	return string(column)
}

func Where(column Column, value any) map[string]any {
	return map[string]any{string(column): value}
}

func And(filters ...map[string]any) map[string]any {
	result := make(map[string]any)
	for _, filter := range filters {
		for column, value := range filter {
			result[column] = value
		}
	}
	return result
}

var sqlPluginSQLColumnNames = []string{"\"plugin\"", "\"update_at\"", "\"created_at\""}

var sqlPluginSQLSearchColumns = []string{}

const sqlPluginSQLSelectStatement = `SELECT "plugin", "update_at", "created_at" FROM "sql_plugin"`

const sqlPluginSQLOrderByColumn = `"plugin"`

var sqlPluginSQLCreateStatements = []string{
	`CREATE TABLE IF NOT EXISTS "sql_plugin" (
    "plugin" JSONB NOT NULL,
    "update_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
}

const sqlPluginSQLInsertStatement = `INSERT INTO "sql_plugin" ("plugin", "update_at", "created_at") VALUES ($1::JSONB, $2, $3);`

var sqlPluginSQLUpdateColumnIndexes = []int{0, 1, 2}
