// Code generated by RPL. DO NOT EDIT.
package sql

import (
	"context"
	"fmt"
	modelpkg "github.com/caramelang/caramel/internal/models/plugins"
	"sort"
	"strings"
)

// pluginsSQLBuildWhere собирает SQL WHERE-часть и аргументы из карты фильтров.
func pluginsSQLBuildWhere(filters map[string]any, startIndex int) (string, []any, error) {
	if len(filters) == 0 {
		return "", nil, nil
	}

	keys := make([]string, 0, len(filters))
	for key := range filters {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	parts := make([]string, 0, len(keys))
	args := make([]any, 0, len(keys))

	for _, key := range keys {
		column, ok := pluginsSQLNormalizeColumnName(key)
		if !ok {
			return "", nil, fmt.Errorf("unknown sql filter column %q", key)
		}

		value, err := pluginsSQLNormalizeFilterValue(key, filters[key])
		if err != nil {
			return "", nil, err
		}

		if value == nil {
			parts = append(parts, column+" IS NULL")
			continue
		}

		args = append(args, value)
		parts = append(parts, fmt.Sprintf("%s = %s", column, pluginsSQLPlaceholder(column, startIndex+len(args)-1)))
	}

	return " WHERE " + strings.Join(parts, " AND "), args, nil
}

// pluginsSQLAppendPagination безопасно добавляет LIMIT/OFFSET для выбранного SQL-диалекта.
func pluginsSQLAppendPagination(query string, args []any, limit int, offset int) (string, []any) {
	if limit > 0 {
		args = append(args, limit)
		query += " LIMIT " + pluginsSQLPlaceholder("", len(args))
	}
	if offset > 0 && limit <= 0 {
		query += " LIMIT -1"
	}
	if offset > 0 {
		args = append(args, offset)
		query += " OFFSET " + pluginsSQLPlaceholder("", len(args))
	}
	return query, args
}

// pluginsSQLQueryMany выполняет SQL-запрос и собирает список моделей Plugins.
func pluginsSQLQueryMany(ctx context.Context, db Executor, query string, args ...any) ([]modelpkg.Plugins, error) {
	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]modelpkg.Plugins, 0)
	for rows.Next() {
		var item modelpkg.Plugins
		if err := pluginsSQLScan(rows, &item); err != nil {
			return nil, err
		}
		items = append(items, item)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// SQLInit создает таблицу и вспомогательные индексы для модели Plugins.
func Init(ctx context.Context, db Executor) error {
	for _, statement := range pluginsSQLCreateStatements {
		if strings.TrimSpace(statement) == "" {
			continue
		}

		if _, err := db.ExecContext(ctx, statement); err != nil {
			return err
		}
	}

	return nil
}

// SQLCreate вставляет текущую модель Plugins в базу данных.
func Create(ctx context.Context, db Executor, model modelpkg.Plugins) error {
	values, err := pluginsSQLDriverValues(model)
	if err != nil {
		return err
	}

	_, err = db.ExecContext(ctx, pluginsSQLInsertStatement, values...)
	return err
}

// SQLGet находит одну модель Plugins по фильтрам.
func Get(ctx context.Context, db Executor, filters map[string]any) (modelpkg.Plugins, error) {
	if len(filters) == 0 {
		return modelpkg.Plugins{}, fmt.Errorf("SQLGet requires at least one filter")
	}

	where, args, err := pluginsSQLBuildWhere(filters, 1)
	if err != nil {
		return modelpkg.Plugins{}, err
	}

	query := pluginsSQLSelectStatement + where + " LIMIT 1"
	row := db.QueryRowContext(ctx, query, args...)
	var item modelpkg.Plugins
	if err := pluginsSQLScan(row, &item); err != nil {
		return modelpkg.Plugins{}, err
	}

	return item, nil
}

// SQLUpdate обновляет запись модели Plugins по переданным фильтрам.
func Update(ctx context.Context, db Executor, model modelpkg.Plugins, filters map[string]any) error {
	if len(filters) == 0 {
		return fmt.Errorf("SQLUpdate requires at least one filter")
	}

	assignments, args, err := pluginsSQLBuildUpdateAssignments(model, 1)
	if err != nil {
		return err
	}

	where, whereArgs, err := pluginsSQLBuildWhere(filters, len(args)+1)
	if err != nil {
		return err
	}

	query := "UPDATE " + pluginsSQLTableName + " SET " + assignments + where
	_, err = db.ExecContext(ctx, query, append(args, whereArgs...)...)
	return err
}

// SQLDelete удаляет записи модели Plugins по фильтрам.
func Delete(ctx context.Context, db Executor, filters map[string]any) error {
	if len(filters) == 0 {
		return fmt.Errorf("SQLDelete requires at least one filter")
	}

	where, args, err := pluginsSQLBuildWhere(filters, 1)
	if err != nil {
		return err
	}

	query := "DELETE FROM " + pluginsSQLTableName + where
	_, err = db.ExecContext(ctx, query, args...)
	return err
}

// SQLList возвращает список моделей Plugins с пагинацией.
func List(ctx context.Context, db Executor, limit int, offset int) ([]modelpkg.Plugins, error) {
	query := pluginsSQLSelectStatement
	if orderBy := pluginsSQLOrderByColumn; orderBy != "" {
		query += " ORDER BY " + orderBy
	}

	query, args := pluginsSQLAppendPagination(query, nil, limit, offset)

	return pluginsSQLQueryMany(ctx, db, query, args...)
}

// SQLSearch ищет модели Plugins по текстовому запросу.
func Search(ctx context.Context, db Executor, term string, limit int, offset int) ([]modelpkg.Plugins, error) {
	trimmed := strings.TrimSpace(term)
	if trimmed == "" || len(pluginsSQLSearchColumns) == 0 {
		return List(ctx, db, limit, offset)
	}

	pattern := "%" + trimmed + "%"
	parts := make([]string, 0, len(pluginsSQLSearchColumns))
	args := make([]any, 0, len(pluginsSQLSearchColumns)+2)
	for _, column := range pluginsSQLSearchColumns {
		args = append(args, pattern)
		parts = append(parts, fmt.Sprintf("LOWER(%s) LIKE LOWER(%s)", column, pluginsSQLPlaceholder(column, len(args))))
	}

	query := pluginsSQLSelectStatement + " WHERE (" + strings.Join(parts, " OR ") + ")"
	if orderBy := pluginsSQLOrderByColumn; orderBy != "" {
		query += " ORDER BY " + orderBy
	}
	query, args = pluginsSQLAppendPagination(query, args, limit, offset)

	return pluginsSQLQueryMany(ctx, db, query, args...)
}

// Store хранит SQL executor для операций модели Plugins.
type Store struct {
	db Executor
}

// NewStore создает SQL store для модели Plugins.
func NewStore(db Executor) *Store {
	return &Store{db: db}
}

func (store *Store) executor() (Executor, error) {
	if store == nil || store.db == nil {
		return nil, fmt.Errorf("sql store executor is nil")
	}
	return store.db, nil
}

func (store *Store) DB() Executor {
	if store == nil {
		return nil
	}
	return store.db
}

func (store *Store) WithExecutor(db Executor) *Store {
	return NewStore(db)
}

func (store *Store) Init(ctx context.Context) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Init(ctx, db)
}

func (store *Store) Create(ctx context.Context, model modelpkg.Plugins) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Create(ctx, db, model)
}

func (store *Store) Get(ctx context.Context, filters map[string]any) (modelpkg.Plugins, error) {
	db, err := store.executor()
	if err != nil {
		return modelpkg.Plugins{}, err
	}
	return Get(ctx, db, filters)
}

func (store *Store) Update(ctx context.Context, model modelpkg.Plugins, filters map[string]any) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Update(ctx, db, model, filters)
}

func (store *Store) Delete(ctx context.Context, filters map[string]any) error {
	db, err := store.executor()
	if err != nil {
		return err
	}
	return Delete(ctx, db, filters)
}

func (store *Store) List(ctx context.Context, limit int, offset int) ([]modelpkg.Plugins, error) {
	db, err := store.executor()
	if err != nil {
		return nil, err
	}
	return List(ctx, db, limit, offset)
}

func (store *Store) Search(ctx context.Context, term string, limit int, offset int) ([]modelpkg.Plugins, error) {
	db, err := store.executor()
	if err != nil {
		return nil, err
	}
	return Search(ctx, db, term, limit, offset)
}
