// Code generated by RPL. DO NOT EDIT.
package sql

import (
	"encoding/json"
	"fmt"
	modelpkg "github.com/caramelang/caramel/internal/models/plugins"
	"strings"
)

// sqlDriverValues подготавливает значения модели Plugins для SQL-запросов.
func pluginsSQLDriverValues(model modelpkg.Plugins) ([]any, error) {
	values := make([]any, 0, len(pluginsSQLColumnNames))
	payloadPlugins, err := pluginsSQLMarshalJSON(model.Plugins)
	if err != nil {
		return nil, err
	}
	values = append(values, payloadPlugins)
	return values, nil
}

// pluginsSQLPlaceholder строит SQL placeholder для конкретной колонки.
func pluginsSQLPlaceholder(columnName string, index int) string {
	_, _ = columnName, index
	return "?"
}

// pluginsSQLNormalizeColumnName нормализует имя поля модели в имя SQL-колонки.
func pluginsSQLNormalizeColumnName(name string) (string, bool) {
	switch strings.TrimSpace(name) {
	case "Plugins", "plugins":
		return "\"plugins\"", true
	default:
		return "", false
	}
}

// pluginsSQLNormalizeFilterValue приводит значение фильтра к SQL-совместимому виду.
func pluginsSQLNormalizeFilterValue(columnName string, value any) (any, error) {
	column, ok := pluginsSQLNormalizeColumnName(columnName)
	if !ok {
		return nil, fmt.Errorf("unknown sql filter column %q", columnName)
	}
	if value == nil {
		return nil, nil
	}
	switch column {
	case "\"plugins\"":
		return pluginsSQLMarshalJSON(value)
	default:
		return value, nil
	}
}

// sqlBuildUpdateAssignments подготавливает SET-часть UPDATE для модели Plugins.
func pluginsSQLBuildUpdateAssignments(model modelpkg.Plugins, startIndex int) (string, []any, error) {
	values, err := pluginsSQLDriverValues(model)
	if err != nil {
		return "", nil, err
	}
	pluginsSQLTouchUpdatedAt(values)
	if len(pluginsSQLUpdateColumnIndexes) == 0 {
		return "", nil, fmt.Errorf("model Plugins has no mutable SQL columns")
	}

	columns := pluginsSQLColumnNames
	parts := make([]string, 0, len(pluginsSQLUpdateColumnIndexes))
	args := make([]any, 0, len(pluginsSQLUpdateColumnIndexes))

	for _, index := range pluginsSQLUpdateColumnIndexes {
		column := columns[index]
		parts = append(parts, fmt.Sprintf("%s = %s", column, pluginsSQLPlaceholder(column, startIndex+len(args))))
		args = append(args, values[index])
	}

	return strings.Join(parts, ", "), args, nil
}

// sqlScan заполняет модель Plugins данными из SQL scanner.
func pluginsSQLScan(scanner interface{ Scan(dest ...any) error }, model *modelpkg.Plugins) error {
	var pluginsRaw any
	if err := scanner.Scan(&pluginsRaw); err != nil {
		return err
	}
	if err := pluginsSQLDecodeJSON(pluginsRaw, &model.Plugins); err != nil {
		return err
	}
	return nil
}

func pluginsSQLTouchUpdatedAt(values []any) {
	_ = values
}

// pluginsSQLMarshalJSON сериализует значение в JSON-строку для SQL хранения.
func pluginsSQLMarshalJSON(value any) (string, error) {
	body, err := json.Marshal(value)
	if err != nil {
		return "", err
	}

	return string(body), nil
}

// pluginsSQLDecodeJSON восстанавливает JSON-значение из сырого SQL-поля.
func pluginsSQLDecodeJSON(value any, target any) error {
	body, err := pluginsSQLRawBytes(value)
	if err != nil {
		return err
	}
	if len(body) == 0 {
		return nil
	}

	return json.Unmarshal(body, target)
}

// pluginsSQLRawBytes приводит сырое SQL-значение к байтам.
func pluginsSQLRawBytes(value any) ([]byte, error) {
	switch typed := value.(type) {
	case nil:
		return nil, nil
	case []byte:
		return typed, nil
	case string:
		return []byte(typed), nil
	default:
		return nil, fmt.Errorf("unsupported raw sql value %T", value)
	}
}
