// Code generated by RPL. DO NOT EDIT.
package sql

import (
	"context"
	stdsql "database/sql"
)

type Executor interface {
	ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *stdsql.Row
}

const TableName = "Plugins"

const pluginsSQLTableName = "\"Plugins\""

type Column string

const (
	ColumnPlugins Column = "plugins"
)

func (column Column) String() string {
	return string(column)
}

func Where(column Column, value any) map[string]any {
	return map[string]any{string(column): value}
}

func And(filters ...map[string]any) map[string]any {
	result := make(map[string]any)
	for _, filter := range filters {
		for column, value := range filter {
			result[column] = value
		}
	}
	return result
}

var pluginsSQLColumnNames = []string{"\"plugins\""}

var pluginsSQLSearchColumns = []string{}

const pluginsSQLSelectStatement = `SELECT "plugins" FROM "Plugins"`

const pluginsSQLOrderByColumn = `"plugins"`

var pluginsSQLCreateStatements = []string{
	`CREATE TABLE IF NOT EXISTS "Plugins" (
    "plugins" TEXT NOT NULL
);`,
}

const pluginsSQLInsertStatement = `INSERT INTO "Plugins" ("plugins") VALUES (?);`

var pluginsSQLUpdateColumnIndexes = []int{0}
