// Code generated by RPL. DO NOT EDIT.
package sql

import (
	stdsql "database/sql"
	"fmt"
	modelpkg "github.com/caramelang/caramel/internal/models/cache_cli_text"
	"strings"
	"time"
)

// sqlDriverValues подготавливает значения модели CacheCliText для SQL-запросов.
func cacheCliTextSQLDriverValues(model modelpkg.CacheCliText) ([]any, error) {
	values := make([]any, 0, len(cacheCliTextSQLColumnNames))
	now := time.Now()
	values = append(values, model.Lang)
	values = append(values, model.OriginalText)
	values = append(values, model.Text)
	if model.CreatedAt.IsZero() {
		values = append(values, now)
	} else {
		values = append(values, model.CreatedAt)
	}
	return values, nil
}

// cacheCliTextSQLPlaceholder строит SQL placeholder для конкретной колонки.
func cacheCliTextSQLPlaceholder(columnName string, index int) string {
	_, _ = columnName, index
	return "?"
}

// cacheCliTextSQLNormalizeColumnName нормализует имя поля модели в имя SQL-колонки.
func cacheCliTextSQLNormalizeColumnName(name string) (string, bool) {
	switch strings.TrimSpace(name) {
	case "Lang", "lang":
		return "\"lang\"", true
	case "OriginalText", "original_text":
		return "\"original_text\"", true
	case "Text", "text":
		return "\"text\"", true
	case "CreatedAt", "created_at":
		return "\"created_at\"", true
	default:
		return "", false
	}
}

// cacheCliTextSQLNormalizeFilterValue приводит значение фильтра к SQL-совместимому виду.
func cacheCliTextSQLNormalizeFilterValue(columnName string, value any) (any, error) {
	column, ok := cacheCliTextSQLNormalizeColumnName(columnName)
	if !ok {
		return nil, fmt.Errorf("unknown sql filter column %q", columnName)
	}
	if value == nil {
		return nil, nil
	}
	switch column {
	default:
		return value, nil
	}
}

// sqlBuildUpdateAssignments подготавливает SET-часть UPDATE для модели CacheCliText.
func cacheCliTextSQLBuildUpdateAssignments(model modelpkg.CacheCliText, startIndex int) (string, []any, error) {
	values, err := cacheCliTextSQLDriverValues(model)
	if err != nil {
		return "", nil, err
	}
	cacheCliTextSQLTouchUpdatedAt(values)
	if len(cacheCliTextSQLUpdateColumnIndexes) == 0 {
		return "", nil, fmt.Errorf("model CacheCliText has no mutable SQL columns")
	}

	columns := cacheCliTextSQLColumnNames
	parts := make([]string, 0, len(cacheCliTextSQLUpdateColumnIndexes))
	args := make([]any, 0, len(cacheCliTextSQLUpdateColumnIndexes))

	for _, index := range cacheCliTextSQLUpdateColumnIndexes {
		column := columns[index]
		parts = append(parts, fmt.Sprintf("%s = %s", column, cacheCliTextSQLPlaceholder(column, startIndex+len(args))))
		args = append(args, values[index])
	}

	return strings.Join(parts, ", "), args, nil
}

// sqlScan заполняет модель CacheCliText данными из SQL scanner.
func cacheCliTextSQLScan(scanner interface{ Scan(dest ...any) error }, model *modelpkg.CacheCliText) error {
	var langValue string
	var originalTextValue string
	var textValue string
	var createdAtValue stdsql.NullTime
	if err := scanner.Scan(&langValue, &originalTextValue, &textValue, &createdAtValue); err != nil {
		return err
	}
	model.Lang = langValue
	model.OriginalText = originalTextValue
	model.Text = textValue
	if !createdAtValue.Valid {
		return fmt.Errorf("required sql time column %q was NULL", "created_at")
	}
	model.CreatedAt = createdAtValue.Time
	return nil
}

func cacheCliTextSQLTouchUpdatedAt(values []any) {
	_ = values
}
