// Code generated by RPL. DO NOT EDIT.
// Generated at: 2026-07-22T01:30:42+03:00
// RPL version: 0.7.3
// Author: <rpl>
package pluginpubinfo

import (
	typespkg "github.com/caramelang/caramel/internal/models/types"
)

// TypePlugin переэкспортирует shared RPL enum `TypePlugin` внутри model package.
type TypePlugin = typespkg.TypePlugin

const TypePluginUnknown = typespkg.TypePluginUnknown

const TypePluginLE = typespkg.TypePluginLE

const TypePluginGLP = typespkg.TypePluginGLP

const TypePluginAPIP = typespkg.TypePluginAPIP

const TypePluginWBC = typespkg.TypePluginWBC

var TypePluginValues = typespkg.TypePluginValues

var ParseTypePlugin = typespkg.ParseTypePlugin

// PluginPubInfo описывает сгенерированную модель данных.
type PluginPubInfo struct {
	Type    TypePlugin
	Name    string
	Author  string
	Version string
}
