// Code generated by RPL. DO NOT EDIT.
// Generated at: 2026-07-17T14:53:23+03:00
// RPL version: 0.7.0
// Author: <rpl>
package cacheclitext

import (
	"time"
)

// CacheCliText описывает сгенерированную модель данных.
type CacheCliText struct {
	Lang      string
	Text      string
	CreatedAt time.Time
}
