// Code generated by RPL. DO NOT EDIT.
// Generated at: 2026-07-22T01:30:42+03:00
// RPL version: 0.7.3
// Author: <rpl>
package sqlplugin

import (
	"github.com/caramelang/caramel/internal/models/plugin"
	"time"
)

// SqlPlugin описывает сгенерированную модель данных.
type SqlPlugin struct {
	Plugin    plugin.Plugin
	UpdateAt  time.Time
	CreatedAt time.Time
}
